<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250401191656 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE cidade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cid_nome VARCHAR(200) NOT NULL, cod_uf VARCHAR(2) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE endereco (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, end_tipo_logradouro VARCHAR(50) NOT NULL, end_logradouro VARCHAR(200) NOT NULL, end_numero INT NOT NULL, end_bairro VARCHAR(100) NOT NULL, cid_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F8E0D60E86C4B51D ON endereco (cid_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE foto_pessoa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ft_data TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ft_bucket VARCHAR(50) DEFAULT NULL, dt_hash VARCHAR(50) DEFAULT NULL, ft_url TEXT DEFAULT NULL, pes_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_2F0E01DBBB8470F ON foto_pessoa (pes_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE lotacao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lot_data_lotacao DATE NOT NULL, lot_data_remocao DATE DEFAULT NULL, lot_portaria VARCHAR(100) DEFAULT NULL, pes_id INT NOT NULL, unid_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4C6AC15FBB8470F ON lotacao (pes_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4C6AC15FA8A42792 ON lotacao (unid_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE pessoa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pes_nome VARCHAR(200) NOT NULL, pes_data_nascimento DATE NOT NULL, pes_sexo VARCHAR(9) NOT NULL, pes_mae VARCHAR(200) NOT NULL, pes_pai VARCHAR(200) DEFAULT NULL, ft_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1CDFAB82AD0D5E19 ON pessoa (ft_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE pessoa_endereco (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pes_id INT NOT NULL, end_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_403BF131BB8470F ON pessoa_endereco (pes_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_403BF131E2BD8A10 ON pessoa_endereco (end_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE servidor_efetivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, se_matricula VARCHAR(20) NOT NULL, pes_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C379765BB8470F ON servidor_efetivo (pes_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE servidor_temporario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, st_data_admissao DATE NOT NULL, st_data_demissao DATE DEFAULT NULL, pes_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1CEAA245BB8470F ON servidor_temporario (pes_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE unidade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unid_nome VARCHAR(200) NOT NULL, unid_sigla VARCHAR(20) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE unidade_endereco (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unid_id INT NOT NULL, end_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E153544A8A42792 ON unidade_endereco (unid_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5E153544E2BD8A10 ON unidade_endereco (end_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE endereco ADD CONSTRAINT FK_F8E0D60E86C4B51D FOREIGN KEY (cid_id) REFERENCES cidade (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE foto_pessoa ADD CONSTRAINT FK_2F0E01DBBB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lotacao ADD CONSTRAINT FK_4C6AC15FBB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lotacao ADD CONSTRAINT FK_4C6AC15FA8A42792 FOREIGN KEY (unid_id) REFERENCES unidade (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa ADD CONSTRAINT FK_1CDFAB82AD0D5E19 FOREIGN KEY (ft_id) REFERENCES foto_pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa_endereco ADD CONSTRAINT FK_403BF131BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa_endereco ADD CONSTRAINT FK_403BF131E2BD8A10 FOREIGN KEY (end_id) REFERENCES endereco (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE servidor_efetivo ADD CONSTRAINT FK_C379765BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE servidor_temporario ADD CONSTRAINT FK_1CEAA245BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE unidade_endereco ADD CONSTRAINT FK_5E153544A8A42792 FOREIGN KEY (unid_id) REFERENCES unidade (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE unidade_endereco ADD CONSTRAINT FK_5E153544E2BD8A10 FOREIGN KEY (end_id) REFERENCES endereco (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE endereco DROP CONSTRAINT FK_F8E0D60E86C4B51D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE foto_pessoa DROP CONSTRAINT FK_2F0E01DBBB8470F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FBB8470F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FA8A42792
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa DROP CONSTRAINT FK_1CDFAB82AD0D5E19
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131BB8470F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131E2BD8A10
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE servidor_efetivo DROP CONSTRAINT FK_C379765BB8470F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE servidor_temporario DROP CONSTRAINT FK_1CEAA245BB8470F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE unidade_endereco DROP CONSTRAINT FK_5E153544A8A42792
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE unidade_endereco DROP CONSTRAINT FK_5E153544E2BD8A10
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE cidade
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE endereco
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE foto_pessoa
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE lotacao
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE pessoa
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE pessoa_endereco
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE servidor_efetivo
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE servidor_temporario
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE unidade
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE unidade_endereco
        SQL);
    }
}
